version: '3.9'
services:
  api:
    container_name: api
    build: .
    ports:
      - 80:8000
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - dev.env
 
  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: master
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080


volumes:
  dbdata: