version: '3.9'
services:

  loadbalancer:
    container_name: loadbalancer
    build:
      context: .
      dockerfile: ./Docker/Nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./Docker/Nginx/nginx.conf:/etc/nginx/nginx.conf

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10-management
    env_file:
      - dev.env      
    ports:
      - 5672:5672
      - 15672:15672

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Docker/Python_api/Dockerfile
    ports:
      - 81:8000
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - dev.env

  email_sender:
    container_name: email_sender
    build:
      context: .
      dockerfile: ./Docker/Python_email_sender/Dockerfile
    ports:
      - 82:8001
    volumes:
      - .:/app
    env_file:
      - dev.env
    depends_on:
      - rabbitmq

  frontend:
    container_name: front
    build:
      context: .
      dockerfile: ./Docker/React/Dockerfile
    ports:
      - 3000:3000
    environment:
      WATCHPACK_POLLING: "true"
    volumes:
      - ./frontend/:/app
 
  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: master
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080


volumes:
  dbdata: