name: API - build

on:
  pull_request:
    paths:
    - 'api/**'

jobs:     
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@main
     
    - name: Build api image
      run: |
        docker build . -f Dockerfile.back.dev -t api