name: API - build and push

on:
  pull_request:
    paths:
    - 'api/*'

jobs:     
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@main
     
    - name: Build api image
      run: |
        docker build . -f Dockerfile.dev -t ${{ secrets.DOCKER_LOGIN_SERVER }}/api:${{ secrets.APIMINVERSION }}
    #- name: Login to ACR
    #  uses: azure/docker-login@v1
    #  with:
    #    login-server: ${{ secrets.DOCKER_LOGIN_SERVER }}
    #    username: ${{ secrets.DOCKER_ADMIN_USERNAME }}
    #    password: ${{ secrets.DOCKER_ADMIN_PASSWORD }}
    #    
    #- name: Push API image to ACR
    #  run: |
    #    docker push ${{ secrets.DOCKER_LOGIN_SERVER }}/api:${{ secrets.APIMINVERSION }}

  #update-image-version-secret:
  #  needs: [build-and-push]
  #  runs-on: ubuntu-latest
  #  steps:
  #  - name: Update minor image version secret
  #    uses: hmanzur/actions-set-secret@v2.0.0
  #    with:
  #      name: 'APIMINVERSION'
  #      value: $((${{ secrets.APIMINVERSION }}+1))
  #      repository: Retoxx-dev/Project-F
  #      token: ${{ secrets.TOKEN }}