---
name: CI prod images check

on:
  pull_request:
    paths:
      - 'api/**'
      - 'mail_sender/*'
      - 'Docker/**'

jobs:
  build-API:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Action
        uses: actions/checkout@main

      - name: Build API prod image
        run: |
          docker build -f ./Docker/Prod/API/Dockerfile -t api:${ GITHUB_SHA::5 } .

      - name: Build Mail sender prod image
        run: |
          docker build -f ./Docker/Prod/Email_sender/Dockerfile -t email_sender:${ GITHUB_SHA::5 } .

      - name: Build Nginx prod image
        run: |
          docker build -f ./Docker/Prod/Nginx/Dockerfile -t nginx:${ GITHUB_SHA::5 } .
