---
name: CI prod images check

on:
  pull_request:
    paths:
      - 'api/**'
      - 'mail_sender/*'
      - 'Docker/**'
      - 'auth/**'

jobs:
  build-prod-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Action
        uses: actions/checkout@main

      - name: Build API prod image
        run: |
          docker build -f ./Docker/Prod/API/Dockerfile -t api:${{ github.sha }} .

      - name: Build Auth prod image
        run: |
          docker build -f ./Docker/Prod/Auth/Dockerfile -t auth:${{ github.sha }} .

      - name: Build Mail sender prod image
        run: |
          docker build -f ./Docker/Prod/Email_sender/Dockerfile -t email_sender:${{ github.sha }} .

      - name: Build Nginx prod image
        run: |
          docker build -f ./Docker/Prod/Nginx/Dockerfile -t nginx:${{ github.sha }} .
